In [5]:
import numpy as np
a = np.array([[1, 3,"hello"], [3, 5, 2], [3,5, 5]])
print(a, a.ndim, a.shape, a.size)  # np.reshape(a,(3,3)
print(f"\n{np.transpose(a)}")
print(f"\n{a[-1:]}")

[['1' '3' 'hello']
 ['3' '5' '2']
 ['3' '5' '5']] 2 (3, 3) 9

[['1' '3' '3']
 ['3' '5' '5']
 ['hello' '2' '5']]

[['3' '5' '5']]


In [39]:
a = np.array([1,2,3,4,5],dtype = np.float32)
print(a)

[1. 2. 3. 4. 5.]


In [15]:
a = np.random.rand(4,3)
print(a)

[[0.20149645 0.84575684 0.40958759]
 [0.32479101 0.18570974 0.09193927]
 [0.97512894 0.10460205 0.17517251]
 [0.54685791 0.02639687 0.64433702]]


In [17]:
a = np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [25]:
a = np.random.randint(5,size=(3,3))
print(f"{a}\n")
b = np.full((3,3),1)
print(b)

[[2 4 1]
 [3 2 2]
 [1 2 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
a = np.eye(3) # identity matrix
#a = np.eye(3,k=2) here 2 gives right shift and -2 gives left shift
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
